name: Update IServ Monthly Stats

on:
  schedule:
    - cron: '0 8 1 * *'  # Her ayın 1’i 08:00'de
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas requests beautifulsoup4 openpyxl

    - name: Run update script
      run: python update_iserv_stats.py

    - name: Commit updated Excel
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add iserv_stats.xlsx
        git commit -m "Update monthly IServ stats"
        git push
